data_path: ./data/input.txt
batch_size: 32  # how many independent sequences will we process in parallel?
block_size: 8  # what is the maximum context length for predictions?
max_iters: 500
eval_interval: 100
learning_rate: 0.001
eval_iters: 200
train_size: 0.9
n_embd: 32
n_head: 4
n_layer: 2
dropout: 0.1